### PR TITLE
Add Support For Documentation

### PR DESCRIPTION
**Pull request by khajavi**

### CODE REVIEW

**Comment by myazinn** [comment]
Hi @khajavi
Is `zio-sbt-website` used only for autogeneration of github workflow and README file or it also does something else?
I see that it can alos generate a website, but couldn't make it work locally to see what it does 🤔 I see that PR is still in draft status, but just curios of what you are trying to achieve

**Comment by khajavi** [comment]
Hi @myazinn 
The work is far from being ready, but the goal is to have zio.dev/zio-intellij home page like other projects (e.g. https://zio.dev/zio-logging/)
`zio-sbt-website` is for the website and also the readme generation.

**Comment by myazinn** [comment]
@khajavi that's awesome, thank you for the explanation

**Comment by hmemcpy** [comment]
While this project is a part of the ZIO organization, it's not a library, and does not need a docs landing page. I'll close this PR for now. Thanks anyway!

**Pull request closed without merging**
