### PR TITLE
Detect duplicate issues

### PR DESCRIPTION
**Pull request by nightscape**
The issues section is swamped by duplicates create through Intellij's "Report issue" feature.
This Github actions tries to detect duplicates and posts them as a comment with a call to action to deduplicate.
@hmemcpy hope this one doesn't get covered by the noise 😉

### CODE REVIEW

**Comment by hmemcpy** [comment]
Oh wow, this looks very cool! I am using the same title for all the automated issues, but the contents may be different. Do you know if it looks at the body of the issue as well?

**Comment by timaliberdov** [comment]
Seems like it only checks titles:
https://github.com/wow-actions/potential-duplicates/blob/7bdfe616364c95f3de680a87123fcd6bf138e796/src/action.ts#L32

**Comment by hmemcpy** [comment]
Right. I might be able to change reporting to put the exception message in the title, this might help!

**Comment by hmemcpy** [comment]
Hey, thanks for the PR, and sorry I couldn't merge it until now! Let's hope this works ;)

**Pull request merged**
