### PR TITLE
Add support for `accessibleM` and `accessibleMM`

### PR DESCRIPTION
**Pull request by myazinn**

### CODE REVIEW

**Comment by hmemcpy** [comment]
WTF clabot

**Comment by myazinn** [comment]
@hmemcpy clabot is fine now, but I have no idea what is wrong with CI checks

**Comment by hmemcpy** [comment]
CI checks are down because github actions deprecated something that we used :(
I need to get to it...

**Comment by hmemcpy** [comment]
Hey, sorry for not attending to this, had to shave the github actions yak. Could you rebase?

**Pull request merged**
